# Generated by Django 5.2 on 2025-05-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='dishOfTheDay',
            field=models.BooleanField(default=False),
        ),
    ]
