# Generated by Django 5.2 on 2025-05-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tickets_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='topic',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
    ]
