# Generated by Django 5.2 on 2025-05-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
