# Generated by Django 5.2.1 on 2025-05-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_dishes_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='vegan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dish',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
