# Generated by Django 5.2 on 2025-05-16 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='menu',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='nickname',
        ),
    ]
